[package]
name = "bmpf-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
ziggurat-rs = { path = "../ziggurat-rs" }

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
